language: python
python:
- '3.6'
branches:
  only:
  - master
env:
  global:
  - secure: "OR+c6jAJUkQy+e57+QzrZHwR4d9LD4RFWvcYJSktPqMrkBtVT3WOd8ZgBZrZcCL/dd5rqlul/7Z8Y+sIQb8sEXLbyjM94e/io6Ut67uMQ//LbCJqR9/C/U6wg8ccid5ue8n7e+ULyBEeo3MpQXSLY/qHqMLVsVJJggrOJVnGoXWsLU4na6wokyxMsuFbR257ooEACFncp3UC4y2FLakh9txixVXZAGPLJ7sWMJgwJokWhnwXq67yvuotGIwha9PqjCf56MzE+bXfP9jIvIgmWyjutE4lCMgStuU0MYl1FTX7M3mLVRiumjF00jkvfQDp8Hin/a1gtBC7rMTTIDZirSn/2kPXnoqMXzvk0xDxrfuuFpQCUq5CrF8cn1v0EeX9rXHK+DcF2ZlOxTlj09tukOFC7lQpGWK8YE8aGUL54YKJJruVxWV9JR4KGa1GMFQ/rYIobq6uvJI4EZPxFCFY4Vd5y1zRqOwSxidNMMqyM+oUXr3C6ETonkH4UEduDSAYxdOa3+Q6FlGvsUjniMt+R347gpU4t03xd7cDdmQi7McOWilBOxdyB9nSsmezO7/ECsQ/mds2Ax74i30XkgWupW9UAekdohfc2R6me2ZTcPAO52QXxCT4jkM3UxYiDhbuFz7QnscemR2tOSjPzkw5hdCUpkgqWclZ9q1j/n7f4IQ="
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Update conda and create test environment
  - conda config --set always_yes yes --set changeps1 no
  - conda env create -q -f environment.yml -n test-environment
  - source activate test-environment
install: true
script:
  - make publish-to-github-force
