language: python
python:
- '3.6'
branches:
  only:
  - master
env:
  global:
  - secure: rVstgv2hpiejKE59tq7M7z7+Wz9OVUSQwCk+mNkWOvokfZ6scOmjwBv7bKtrNMWNCyIUAk9vz/YbvCIq/6ATtASQ+Uqdjq14FEmCp0kAB2hSAEBKV2MRrhl9FCGvm8PX2HHiFpbX8IDKoeO0D4y02aSTB4qzmlJN6o6i27E6XqYS8Uic/LCT+FgVzrf/uNnazWMN2OWuYQ3GhPkc4LSAvwJpE2mRVMGhpl8zvIkE5siQCjba7r822dCkxrsRK+iPxHyvlKygQHjCiTSqDrtYEqm1QK36W9ESXAJPebPUa4anLzyC/OysCfI6a3Pru5Dqha4ajvo3t39hFELvVCxOk+Wlb75OuMS2ZovMl49Q/3SSZSpdnWIoOx1eSB1QtpxTEs4cQ71cF9XwtWkPCBwQIEZFkzZvZaTT45LOhM1Ck0EYYL7t8ZkPuEeZziC3G7djuQQNDgl3iHr+K5o+qFaUfJEdpDiGlxaj3F2fK5jZOM1EFh1FoyXVE83ut94kuO3yzlUXFfgOyRqhSLcgsTR9rv0zH9iTYX5p4DFofT4Z9zucbbY/nbw6j+W9InpLrWDW7P35Yc7Xk8/MfQaaUKoeiL4IBbgaGVwXm/ZIm+ucv2BPltr3S97urvr8hy+78jDfSPhqqpgj5UkuwtYL2p8Lef+dpoQUwFq89HCEXRqqgr0=
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda env create -q -f environment.yml -n test-environment
- source activate test-environment
install: true
script:
- make publish-to-github-force
