language: python
python:
- '3.6'
branches:
  only:
  - master
env:
  global:
  - secure: LBsMie/7/IS9T2Rxb3KtvfLLT9QCxSxx4pujWT9pJxPyEgNb7sLZ0ugEk66w/w6TkoJSvADB0Z+wJBW9VA1qfcZsTs4YKTM3YA6f6spToEe4xOwRXyDWOZ9/Ubw+NiX400Myd4pSYBrDW8bBXyH0Aqb6Al/OwD4E64izUzhNaSRK/a5+dYW9mjM+uJtQwZ+uB7ZCI+Bn+DVxg9Hj26VTyZmXN8Nnwn4e+kfeFrBg6ECwLX9PP/xiOuM4GhecTF2q6xZzo7dBYHbXtiMwHFhxU7oNSykvaJC/IOSrEcVCqPNWxoTCxvnjIvZxjNDRLaZosgHEJEX7N0W/u3prU7DjGjQIJ/cJtM1LRBViffH3iTwpt7Pq/pXQ4mWzF/o6X54/hq9g3EQavurlNVpxjUyMxEUYeQ0JTnM+/R/AojxLeTeyom18AVGXK6tY92VtMLSWnLaIH0rTlNwgAXHw1CwEv/nb264dwVU5Zyg9+YusruaXumckoyWxOMb+UnfYfFWbvghc5HRviflLgWzc1+aJSP8opwZbt4mshNs/uKMqIAywEPS1VEcTFzWCz9Xl29s3rXolOzomUi83VaC0sQr7s78VmANdoUmuSuh6+AQYNERElP/UY5garRb/JJtESlbycYRjQUi9CBOixzL2wab9HB//oMN5xaOr2v7+so6tyrQ=
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda env create -q -f environment.yml -n test-environment
- source activate test-environment
install: true
script:
- make publish-to-github-force
